### ISSUE TITLE
Can view the conference schedule in-app

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#102]
There should be a somewhere (probably the left-side navbar?) that opens a modal with a text description of the event schedule.

Presumably we want this to show the meetup schedule during the meetup, and the real conf schedule during the conf.

Stretch goal: highlight what time it currently is.

**Comment by kawa-kitsuragi** [comment]
Extra stretch goal: would it be possible for all times to be shown in your local time zone? (Note I am *very* aware that time zones are *extremely* annoying to deal with programmatically! But I think it'd be great.) 

I'm feeling inspired by https://gamesdonequick.com/schedule here. Not sure how they do it.

**Comment by lazerwalker** [comment]
Janky and simple, but good enough for now. Includes local time zones.
<img width="813" alt="Screen Shot 2020-08-27 at 12 17 24 AM" src="https://user-images.githubusercontent.com/821238/91383677-bc95de00-e7fa-11ea-84ed-138f58bf53ae.png">
