### ISSUE TITLE
Find some way in the MUD to recognize everyone who has contributed to it!

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#103]

**Comment by kawa-kitsuragi** [comment]
I've had an idea of being able to interact with a version of the Octocat statue that's in the actual Github space, if we continue to use that model. I've imagined user generated content coming through of things the Octocat could say, or jokes to the speakers, or what not. But it would be pretty fun to "ask the Octocat who made the space" and get a list of contributors!

**Comment by lazerwalker** [comment]
For now, we've just got a link to the GH contributors page. Not ideal, but good enough for the meetup?
