### ISSUE TITLE
Should the conference space be set at GitHub?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#108]
For the meetup, probably, unless somebody has a clear vision beyond "let's clean up the current filler text slightly". But for the conf itself...

**Pros to GitHub**
* A fun reference for previous attendees
* Framing the space as an obvious space where a conference would happen is familiar and recognizable for this weird new experience
* If more game-y spaces are more fantastical, that magical realism shift as players move from 'normal' rooms to weirder rooms is a fun way to draw people into the more playful content

**Cons to GitHub**
* It's an in-joke that excludes new attendees, in a year where most attendees will probably be new
* GitHub isn't sponsoring us this year, but we're still giving them free marketing
* Even if we want to design a 'professional conference' space, we might be able to design something better if not hampered by being grounded in GitHub's space
* Is a 'professional conference' space actually what we want, instead of something more fantastical? This isn't a leading question, I legit don't know

**Potential Alternatives**
* It's a convention center / conference space... but Tolkienesque/roguelike fantasy. 
* Spooky dungeon conference center
* Traditional roguelike/fantasy game village, where different rooms are 'shops' / etc.
???

**Comment by lazerwalker** [comment]
I currently mildly feel like "the main space is a professional-feeling conference space, that slowly gives way to more fantastical elements" is the correct choice. Given that, modelling it loosely after GitHub (even if we don't want to make it as explicit) feels like a fun way to wink to our dedicated prior attendees without necessarily isolating new attendees, and helps find some way to stop it from feeling uninterestingly generic.

That said, someone may have an idea that blows that out of the water.

**Comment by annie** [comment]
as a newcomer to the conference, i was pretty confused at first by the GitHub reference! i love the idea of making it more of a generic unnamed conference space that slowly reveals itself to be more fantastical 🙂

**Comment by lazerwalker** [comment]
An obvious-in-retrospect insight: it can still resemble GitHub's space, and have some loving nods to the GitHub space for old-timers, while presenting as a generic conference space instead of being like "WELCOME TO GITHUB HERE IS THE OCTOCAT STATUE"
