### ISSUE TITLE
Seeing some unknown users show up

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#109]
I think I know what's happening. Take the following sequence of events:

Bob is logged on.
Alice says "hello!"
Alice logs off.
Bob refreshes the page.
Bob sees Alice's message as being sent by "unknown".

Bob's message history contains messages from Alice. However, the userMap sent from the server when Bob connects a second time doesn't contain Alice's user ID, since she was not online when he requested a user mapping (which only sends online users for perf reasons)

Potential solution: store the user map in localStorage alongside the message history.

**Comment by MoyTW** [comment]
https://github.com/lazerwalker/azure-mud/pull/111
