### ISSUE TITLE
Profile edit view: make "Description" field larger?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#123]
My assumption/hope is that 'description' will become the catch-all field where culture will spontaneously emerge as the conference goes on (which also maybe suggests a different name from 'description' is needed?)

If that happens, having a single-line to edit might be frustrating. Potentially worth moving this to the bottom and giving it breathing room.

**Comment by apepers** [comment]
Kawa and I were talking and another way to flavour this might be more "This space on your name badge is intentionally left blank - fill in as you like" or just "What else is written on your name badge?"

**Comment by lazerwalker** [comment]
Naively making the description field take up multiple columns with CSS grid causes it to break on mobile. I suspect I could add a media query.
