### ISSUE TITLE
Figure out why AV selector no longer works in Firefox

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#127]
Right now, it immediately crashes because there's a React render loop.

If you remove the `setVideoId(defaultVideo)` etc calls, that removes the initial infinite loop, but trying to change either the audio or video device causes it to rerender itself like 5 times and doesn't actually change the device.

This works in Chrome and Safari. No idea why Firefox is broken.

I feel like I'm dangerously close to burnout, so punting on this, even though it's bad :(

**Comment by MoyTW** [comment]
I think this is..."fixed"? As in I made a change to just not force a default selected device, it seems to have worked and I was able to chat using Firefox during the meetup, and I didn't notice any adverse effects.

I think I'd need somebody with multiple video & audio devices on their machine connected to try this in Firefox but it definitely works for a sample size of n=me.
