### ISSUE TITLE
Admin panel that logs all chat messages

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#13]
* Shove *all* sent messages to a file or database somewhere
* Web UI to view them. Eventually some sort of filtering, but not for now
* A button to delete all of history
* Authentication so only admins can view (not sure if it needs to be per-admin, or just a shared password)
* Audit log indicates when it has been accessed. When you access, must enter a reason. This log is accessible from a public page.

**Comment by MoyTW** [comment]
1. Including notes & profile text changes? For something like this a good rule seems to be "if the user typed in freeform text that got shown, log it".
2. What type of file/database? A couple of viable options seem to be Azure Table Storage or "Azure Database for PostgreSQL"; the table storage would probably be my preference because it seems easier. The schema-less nature might be long-term annoying but I assume we're actually gonna wipe this thing after the event's over so it's fine.
3. Web UI in client is fine? Do we want export functionality? If I had to search down a specific instance having it in a text-friendly manipulable format easily would be really helpful.

**Comment by lazerwalker** [comment]
My idea had been to wrap every endpoint function in a higher-order function (similar to the existing `authenticate` one that injects a full user) that captures all outgoing signalR messages and shoves them somewhere, since that will capture all possible data we need.

The primary use case is going to be looking for messages in a specific room (or DM/whisper session) around a rough time period, so I suspect what's going to be most useful is being able to do a full text search on messages + timestamps, yeah. 

Conceptually, I think it makes sense to think about this as a logging problem. I wonder if it even makes sense to just piggyback on Azure's built-in logging tooling (`context.log` dumps a string into a queryable log system you can access from Application Insights), although that doesn't quite give us the access audit log capabilities a home-built tool would give us.

**Comment by MoyTW** [comment]
I put up a tentative branch here: https://github.com/lazerwalker/azure-mud/compare/logging

Basically, it uses Table Storage to store relevant actions, implemented in `authenticate`. I originally wrote another handler that would sort of just wrap inside of `authenticate` but then I found myself pasting it almost everywhere, anyways, so I figured I'd basically force new endpoints to have to decide whether they wanted this or not.

I'm having a trouble with getting the data back out of the table storage, though, mostly from me maybe not being able to find many examples and the documentation being unhelpful. You can currently just grab it right out of the portal raw using Microsoft Azure Storage Explorer, and do stuff like query on the userId/timestamp. Here's what it looks like right now:

Bad Actor:

![moytwperspective](https://user-images.githubusercontent.com/1434086/90993639-7b879a80-e56a-11ea-8010-bf3a8f6190bb.png)

Mod:

![muffituffiwuffiperspective](https://user-images.githubusercontent.com/1434086/90993637-7aef0400-e56a-11ea-8f99-2b55f2b13ddc.png)

Audit Log:
![azurestorageexplorer](https://user-images.githubusercontent.com/1434086/90993638-7b879a80-e56a-11ea-8a57-fa7fb68903be.png)

The important thing to that this tries to preserve is the audit log lets you reconstruct the state of the relevant data at an arbitrary time - for example, here's Bad Actor creating and deleting an offensive note:

![offensivenote](https://user-images.githubusercontent.com/1434086/90993812-2a2bdb00-e56b-11ea-8332-d57424c551ea.png)

**Comment by lazerwalker** [comment]
Cool, this generally looks good!

I agree the docs here are a bit awkward — my understanding of "Input - usage" on https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table?tabs=javascript is that maybe you're required to set `take` and `filter` when using JS to receive data? I'll poke around some more, and file some bugs with the product team if needed, cause yeah, this is kinda rough.

That said, for the purposes of this week I suspect just accessing through the Azure Portal is probably fine?

**Comment by MoyTW** [comment]
I agree that for the purposes of this week, accessing through the Azure Portal is fine - I hope we won't actually have to use it, it's only 3 hours long.

**Comment by MoyTW** [comment]
MR for write-only section: https://github.com/lazerwalker/azure-mud/pull/174 - this shouldn't close the MR but will be fine for the duration of the 3-hour meetup, hopefully.

Unrelated I also got the input to write and can close that out later, but I think pre-meetup tweaks like making /mods work properly are more urgent, so will defer that.

**Comment by lazerwalker** [comment]
The more I think about this, I think even for the main event we're okay with just relying on the Azure Portal? Like, building out our own UI won't solve the problem that anyone with Azure access can access this data, and I think our engineering time is better spent on things other than building a custom slightly more convenient UI for something we'll (hopefully) rarely use.

Closing now, but happy to reopen.
