### ISSUE TITLE
How do we add more moderators?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#133]
We'll need to be able to give and remove mod access.

Currently, this is a hardcoded list of user IDs (e.g. a long string of numbers) on the server.

Two obvious paths:

1. We maintain that server list. We'll need an easy way for would-be mods to find their user ID to send to me (or someone else) to be added to the list.
2. Mods have in-game UI to add/remove other mods, presumably by clicking their name and having the option in the list.

2 is obviously nicer. I think 1 is fine and probably less work.

**Comment by MoyTW** [comment]
One note in that path #1 is that the server list shouldn't be hardcoded, it should be drawn from redis. You still might need to cowboy around a bit in the redis console to get it done but if it's hardcoded we'd be booting everybody for 30s if we wanted to add a mod.

**Comment by lazerwalker** [comment]
This is now in. Mods have the ability to right-click and add/remove other users as mods.

If we have a bad actor, or someone accidentally removes everyone else and also themself, we can manually re-add via the Redis console.
