### ISSUE TITLE
Blank users in video chat

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#145]
Process:

1. Em enters video chat
2. Kawa enters video chat
3. Em leaves for another room while Kawa connects

Thus: Kawa sees a space for Em in video chat, but it's blank.

![Video chat with a blank space for Em](https://user-images.githubusercontent.com/62489292/91111728-3ab58180-e64f-11ea-8c2d-47325a3e7c98.png)

**Comment by lazerwalker** [comment]
Tracking this over in #158
