### ISSUE TITLE
Better UI for back-and-forth whispering

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#17]
Right now, whispers show up in the chat feed along with all other chat messages. If somebody whispers to you and you want to respond, you need to type `/whisper` or click their name and choose "Whisper".

This is very MUD-y, but makes private 1:1 conversations awkward. We probably want a better UI for this.

Could be some or all of the following:

* There is a selector next to the text box that lets you switch back to talking to everyone (the "normal" MMO design solution)
* After you've whispered to someone, prepopulate the text field with `/whisper user` until you send a non-whisper message
* You can click a whispered message to prepopulate a `/whisper` to the sender
* A dedicated separate UI for viewing 1:1 chats with different people

The last is the most Slack/Discord-y. It's also the most work. It's also the design choice that most encourages people to send a lot of 1:1 messages instead of chatting in public. So there's a philosophical question about what behavior we want to encourage.

**Comment by lazerwalker** [comment]
I think the most important thing here is the last item. I think this is a few things:

1. When you DM someone, or they DM you, programmatically open their profile view in the side pane
2. The profile view screen should show your DM history with that person (read: all `WhisperMessages` either to them or from them) in a scrollable box
3. The profile view should have a separate input + send button that sends a DM to them (read: take the input from the box and prepend "/whisper [username]" before sending to the server)

**Comment by annie** [comment]
am i right in assuming that this only requires a client change? if so, i can work on it next!

**Comment by lazerwalker** [comment]
Yep, this should be client-side only!

**Comment by annie** [comment]
hey sorry for the delay, been a lil burnt out from work 😞   gonna try to get a PR out for this today!

**Comment by lazerwalker** [comment]
No worries! Taking care of yourself is far more important than our silly little project :)

Looking to seeing something when it's ready!
