### ISSUE TITLE
Clients are connecting to videochat without user permission

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#189]
I'm seeing calls to /negotiate on pageload, followed by video presence actions

**Comment by MoyTW** [comment]
I'm trying to reproduce this. I can see the call to `/negotiate` but I cannot see any video presence actions other than it calling `leaveVideoChat` whenever I switch rooms.

I think that `/negotiate` has to do with SignalR and not video chat, so unless I am not understanding what that does I think it's not a problem. The `leaveVideoChat` is annoying and probably unnecessary to send unless you're actually in a video chat but I'm not sure it's causing unauthorized camera/speaker usage.

Can you put more info on this if you have details?

**Comment by lazerwalker** [comment]
I suspect I meant /broadcastPeerId, not /negotiate.

That said, i'm no longer seeing the video presence actions I was definitely seeing before, so I'm okay with tentatively closing this.
