### ISSUE TITLE
The /move command doesn't properly reassign rooms

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#193]
If you /move entryway from lounge, you can't hear what other people are saying/say anything and have other people hear it. It's weird! Refreshing the page fixes it (!??).

So...yeah, chew on that.

**Comment by lazerwalker** [comment]
This seems to only happen on /move. Worth confirming it vs sidebar vs room description links.

**Comment by lazerwalker** [comment]
The `sendChatMessage` function didn't have signalRGroupActions defined as an output. Hopefully adding that fixes this.
