### ISSUE TITLE
Limit text length of messages

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#194]
So that you can't paste, like, All of Shakespeare's Sonnets At Once into the thing

also limit the length of single lines

**Comment by lazerwalker** [comment]
This is a few separate issues:

- [ ] Limit total message length

- [ ] Properly line-break individual lines of text when there are no spaces. There's CSS for this we're using in the note wall we just need to move over

- [ ] There should be a max horizontal width specified for the chat message view. Just setting `overflow-x: hidden` should do it.

**Comment by lazerwalker** [comment]
I looked briefly into line-breaking individual lines of text (e.g. just mash the keyboard with no spaces and watch the message window get wider). 

Right now, as you type a long message, the window just gets wider and wider, even if `overflow-wrap: break-word` is set. Presumably `overflow-x: hidden` does nothing either.

The issue is the way CSS flexbox is intersecting with this, but I don't have experience with flex-box.

**Comment by MoyTW** [comment]
Okay if doing a CSS Thing is for some reason really hard, can we just set an arbitrary limit on single-word length in the client and bump everything that has, like...I dunno, 60 characters?

**Comment by lazerwalker** [comment]
I suspect the underlying CSS issue I’m running into may also be causing other layout issues — I think it’s worth spending some more time trying to get things laying out properly. I can take a look at it later.

**Comment by lazerwalker** [comment]
Yes, I believe I was right :)

Currently having issues where, if my screen isn't super super wide, the chat screen is still fixed to a large width and the sidebar isn't visible.

![Screen Shot 2020-09-25 at 00 33 03](https://user-images.githubusercontent.com/821238/94226879-b9a80f00-fec6-11ea-8226-210aa1a7363d.png)

My strong suspicion is these two are related, and this is a CSS regression introduced in the past few days.

**Comment by lazerwalker** [comment]
![Screen Shot 2020-10-01 at 10 50 58 PM](https://user-images.githubusercontent.com/821238/94883424-a5b95b80-0438-11eb-8823-e248068a758a.png)

Look at the last message. I suspect the reason it's not linebreaking properly is unrelated to these CSS issues, but maybe not?
