### ISSUE TITLE
Limit localstorage length

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#195]
+ Performance got slow
+ I deleted localstorage
+ Performance got fast again

lol there is that explicit note on the state size maybe causing an issue, we should fix

**Comment by kawa-kitsuragi** [comment]
I'd note to please not delete the user's theme preference in the process!!

**Comment by lazerwalker** [comment]
I'm curious if the problem is the amount of space being taken up vs JSON parse time.

Two suggestions:
* Shrink localstorage use massively. Hard-limit the number of messages we store. This probably includes removing DMs entirely, and serving them persistently from the server.
* Investigate alternative local storage options. This likely means using a wrapper around the IndexedDB API

**Comment by MoyTW** [comment]
Okay, I did some perf profiling by injecting hundreds of messages and examining in dev tools and it turns out the issue is *not* that localStorage length or the serializing/deserializing but rather that when you have 500 messages the browser chokes trying to render all 500 messages.

You can demonstrate this easily by injecting tons of messages into the localStorage and then putting `props.messages.slice(-10)` in the return of `ChatView`, and it'll be very quick.

So...the obvious solution is to just never render more than (arbitrary reasonable number) in the scroll?

**Comment by lazerwalker** [comment]
Ahh, really good work!

The "proper" solution would be a combination of switching to IndexedDB (to stop slow writes) plus something like https://github.com/danbovey/react-infinite-scroller to gracefully handle rendering arbitrarily infinite messages. I agree with your course of action, though :)

I'm okay with skipping #4 — our spatial metaphor is already putting a lot of cognitive load on people, I don't necessarily want to expose too many levers and options that we then need to explain.
