### ISSUE TITLE
Distinguish moderators with accessible formatting

### ISSUE THREAD

**Issue by brittag** [lazerwalker/azure-mud#196]
White names vs pink names may be hard to see for people with low vision or colorblindness, so let's distinguish mod names with something more visible! No specific opinions on implementation.

**Comment by kawa-kitsuragi** [comment]
Do you know if including an emoji before a user's name would be clear/better alongside the color?

**Comment by lazerwalker** [comment]
I think emoji or text would solve this. Two concerns are (a) finding something where it's clear what the symbol means and (b) making sure normal users can't impersonate mods.

**Comment by lazerwalker** [comment]
Someone in the feedback wall suggested having mod names be e.g. dark text on a light background. That sort of color solution might be a good compromise.
