### ISSUE TITLE
Store DMs on the server?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#206]
Normal chat being relatively ephemeral is okay, but if we kill localstorage, it'll be really weird seeing previous DMs go away.

Maybe each user can have their own redis key "mailbox" that contains all of their DMs, returned on pageload (probably in a separate network request from /connect, to shorten load times since they're already long)

**Comment by MoyTW** [comment]
Other, easier, option, since I've looked into the localstorage issue - put them under their own key in localstorage? This keeps it in the client.

This does mean if you switch browsers or computers you lose all the data but it's also way faster.
