### ISSUE TITLE
The dance floor should play a Spotify playlist (ask Lee for his retro one?) and there should be a 'dance' button that does something fun

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#224]

**Comment by kawa-kitsuragi** [comment]
Do we want to also include the Funkip DJ sets from past Roguelike Celebrations?

https://soundcloud.com/funkip/rand-gen-mem
https://soundcloud.com/funkip/roguelike-celebration-2018-saturday-night
