### ISSUE TITLE
Speaker Room for moderators and speakers to communicate logistically 'off screen'

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#230]
Brought up in today's Streamyard tests -

A central place for moderators and speakers to communicate things like "hey I'm running late", "don't forget to unmute your microphone", et cetera. Probably a single room locked by permissions? 

Blocked by being able to flag speakers specifically, #134 .

**Comment by lazerwalker** [comment]
One question: I know Streamyard has a max of 10 people on-stream, but do we know if there's a limit to the number of people on the site but not actively streaming?

It's sub-par, but a non-code solution to this might be to just tell speakers "come to the Streamyard chat to talk to us"

**Comment by MoyTW** [comment]
Another no-code option is to create a Discord and invite everybody on speaker + staff.

**Comment by MoyTW** [comment]
Another option: tell them to use `/mods` on the MUD
