### ISSUE TITLE
Add an "it's been a while since the last message" horizontal line

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#232]
Gut instinct: if the previous message timestamp is significantly earlier than the current one (1 hour?) add a message that just renders as a `<hr>`.

**Comment by kawa-kitsuragi** [comment]
It might be nice if an `<hr>` also shows up when you switch rooms, to make it clear your past message history versus what's happening in the present room? Just thinking out loud on this one.

**Comment by lazerwalker** [comment]
Yep, agree! See https://github.com/lazerwalker/azure-mud/issues/155 for more discussion about that.

**Comment by lazerwalker** [comment]
Closing in favor of #155
