### ISSUE TITLE
[Proposal] Visually show entrances/exits from "room"

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#233]
To help with room entry/exit spam, instead of putting the room entry/exits in text, display them like you would a minimap. I think we should *also* have a toggle-able "entry/exit" button that displays the messages so "wait did they leave before/after I said X" can be answered? and I think that's probably helpful whatever we decide to do?

Here be a jank prorotype.

![room](https://user-images.githubusercontent.com/1434086/93687726-a59e8080-fa74-11ea-9e1d-6a1fc8ed67a0.gif)

**Comment by lazerwalker** [comment]
Yeah, I think having main stream enter/exit messages be toggleable makes a lot of sense.

My main concern about a visualization (I'd originally imagined players getting to pick a single ASCII character to represent them, and having usernames on hover) is it's a difficult problem to design something that scales and is both aesthetically pleasing and useful both in a 4-person room and in the theatre with 200-300+ people

**Comment by MoyTW** [comment]
Clearly way out of possibility at this point.
