### ISSUE TITLE
You can change your name to somebody else's name

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#235]
If you have `Alice`, `Bob` and `Bob` changes their name to `Alice`:
* There are two Alices, which is deeply confusing
* All whispers goes to the first Alice and the second Alice can't receive whispers

**Comment by lazerwalker** [comment]
Working on this. Edge cases to account for:

- [ ] If I change my name from Alice to Bob, Charlie should then be able to change their name to Alice (updating a name needs to remove the old name from the user map)
- [ ] If I change my name from Alice to Bob, and then open up the profile edit screen again before refreshing, the text field says Alice. I need to make sure I'm updating all data in local state
- [ ] If you enter an already-used name, we're just showing a JS `alert`. I think that's acceptable, but worth considering
