### ISSUE TITLE
Add a welcome modal explaining the space

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#242]
Already did this (see https://github.com/lazerwalker/azure-mud/pull/241), but opening an issue to track this separately from the larger issue of user onboarding + guiding user behavior towards chatting.

<img width="724" alt="Screen Shot 2020-09-22 at 19 13 19" src="https://user-images.githubusercontent.com/821238/93946803-3b9e0980-fd08-11ea-9a1d-1d1629d0273c.png">

Open to suggestions. I'd be happier if I added a splash of color to break up the text, but I think this is okay for now?

**Comment by MoyTW** [comment]
Maybe mention how to access help?
