### ISSUE TITLE
Find a good monospace typeface we can use, embed it.

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#25]
We should pick our own distinctive beautiful monospace typeface we can embed within the app so everybody gets the same experience.

I think Fira Code is a good choice. Microsoft's Cascadia Code is too. Both are OSS.

We want something with bold and ideally italics.

**Comment by kawa-kitsuragi** [comment]
I'm fond of Roboto Mono: https://fonts.google.com/specimen/Roboto+Mono It does have both italics and bold. Selfishly, I like its @ a little more than Fira's, too! 

Surfing Google Fonts also had me find this, which intrigues me too. I love that the italic actually changes the serifs! (I admittedly don't know the implications of that on an accessibility standpoint, but on an aesthetic one, I'm into it.) https://fonts.google.com/specimen/IBM+Plex+Mono

**Comment by lazerwalker** [comment]
Closing this for now, will re-open when/if if I want to revisit!
