### ISSUE TITLE
Sync Schedule modal

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#253]
If we don't have this by the time the conference rolls around we should either:
1. Rip it out
2. Just give a link to the website

**Comment by lazerwalker** [comment]
Right now, the site has Saturday's schedule hardcoded in, with Sunday's schedule commented out and presumably easy to swap out Saturday night after things end. We'll need to manually update any changes between now and then, but I suspect those changes (if any) will be minimal.

What exactly do you mean by 'sync'?

**Comment by MoyTW** [comment]
...wait. What. Oh. Hey. Okay for some reason the last time I opened schedule my brain processed it as being the Preview's schedule even though it's obviously not.

I meant somebody should take schedule from site -> put into MUD but it's already done, nevermind this issue ('least until somebody has to swap them after Saturday)
