### ISSUE TITLE
Switch Twitch embed to use interactive iframe

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#259]
See https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods

This would make it so that, if you click the new button to pop out the Twitch stream (#210), we can stop the stream playing in the main window.

**Comment by lazerwalker** [comment]
See #238, this may become a question of YouTube embeds.

**Comment by MoyTW** [comment]
Would this also let the popout screen resize? Right now it looks like the popout screen is fixed resolution.

**Comment by lazerwalker** [comment]
I think these are unrelated. 

Right now, there are two ways in which the popout screen is fixed:

* I've explicitly disabled resizing the window. This is easily changeable
* Twitch embeds require a 'width' attribute. This is currently set to the same value in the main window. From documentation, I believe this can be made into a percentage, which in combination with the previous item would allow people to dynamically resize the stream size, but have not tested this.

**Comment by lazerwalker** [comment]
Irrelevant with the switch to YouTube
