### ISSUE TITLE
Remove channel sidebar?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#263]
Pulling out from discussion in #214 where @MoyTW mentioned it.

I'm increasingly wondering if we should remove the left channel sidebar entirely, so the only two ways to navigate are clicking hyperlinks in room descriptions or by viewing the full map.

An original concern was that the space would be too foreign to attendees, and consciously making things look like Slack/Discord would make it more approachable. Instead, we had a lot of people who were confused that it superficially looks like Slack/Discord but behaves differently. Forcing people to interact with the space as a more physical game-like experience would be a (perhaps blunt) tool to drill home that our model isn't Slack/Discord.

Concerns are the same as we originally had: that people will be weirded out that this feels different. I no longer strongly feel this is a problem we'll have in practice; people seem really excited for a new experience, and attendees to a game conference will be able to figure out hyperlinks and/or a map.

If we had another preview event or playtest opportunity, I would 100% be in favor of playtesting this and seeing how it went. As it stands, I'm probably 70% in favor of making the change anyway? Curious to hear thoughts.

If we did this:
* Clickable room names that show up in room descriptions should live-update with user count (this is probably a good idea regardless)
* We might consider making the left sidebar "Map" button a large button with a white border instead of just another list item
* Alternatively, instead of a larger button, we could come up with a mini-map (a la Travis's original prototype) that, even if not very functional, would live in the sidebar and hint at "hey, there's a map you can open/use"

**Comment by MoyTW** [comment]
Boy that's a big change to pull literally 7 days before the conference. Well, *glances at the high priority backlog* at least the list's getting worn down?

If we *can* swing it I'm reasonably sure that we should do this with the caveats of:
* there exists a VERY obvious MAP button with a full map
* there exists a minimap that gives you a room vision radius of 1 (that is you can see every directly linked room)

I think if we do this unless we have somebody get real involved in programatically drawing ASCII graphs we absolutely have to have it not be hand-drawn, because we're probably gonna stuff a couple of extra rooms in there and it's gonna be a pain to resolve.

But we should def. talk about this in the meeting Sunday to get more eyes because I am obviously on the faaaaaar end of game-like v. chat-like.

**Comment by lazerwalker** [comment]
I agree discussion Sunday makes sense!

If we lock down the final room set sooner rather than later, I think resolving a hand-drawn map is doable and is something I'm willing to do.

I think this would be a big conceptual design change, but a fairly minor implementation/engineering change other than figuring out the mini-map. Thinking about it more, I feel like a mini-map in the sidebar would look weird -- I think you're right that having a "MAP" button (presumably in the sidebar) and a mini-map (maybe in the top-left/top-right corner?) as separate items would make sense.

**Comment by lazerwalker** [comment]
Some engineering work has been done to change room hyperlinks in the room descriptions to include number of players and video presence (on the `room-name-views` branch) but I'm currently blocked by what appears to be a bug in the parser I'm now using (see https://github.com/remarkablemark/html-react-parser/issues/168). 

Probably going to move onto higher-priority issues for now rather than try to submit an upstream patch, but keeping an eye on this.

**Comment by kawa-kitsuragi** [comment]
It's worth noting that even right now the 4 game showcase rooms aren't in the ASCII map, and we'd be adding up to 6 unconferencing rooms on top of that as I mentioned in the other issue. Will we have space in our modal for all of this? How should it geographically be organized?

**Comment by MoyTW** [comment]
The modal is already scrollable, the main issue is it always opens at the upper-left corner. We'd need to be able to get it to open centered on you but it's fully functional. See:

![mapmodal](https://user-images.githubusercontent.com/1434086/94386028-784c7500-00fb-11eb-99a7-871206e0b747.png)

**Comment by lazerwalker** [comment]
This is super helpful, the map hasn't needed to scroll on my devices typically so this is useful information that auto-panning in the modal is necessary.

**Comment by lazerwalker** [comment]
I need to think through how to technically implement it in the map, but my general instinct is to basically implement submaps/subareas.

What I'm imagining:

There'll be an unconferencing area that shows up as a single room in the map. When you click on that, you are moved to a sort of lobby for the unconferencing area, whose description includes text links to the sub rooms. Ideally (but perhaps not in the next week) opening the map would then show you a new alternative map of just the unconferencing rooms, with a button to zoom out and look back at the normal map.

This would also apply to showcase rooms (I assume in this case we may want to split back to 1 game per room), and e.g. the example given of different tables in the kitchen.

Except for the map, this is currently implementable just by configuring the rooms correctly. A task on my plate is figuring out the best way to scale the map rendering.

**Comment by MoyTW** [comment]
I am strongly against gating subareas behind a region on the map, mostly because that makes it really hard to discover any single room, and we're leaning towards not just naming the rooms "Room X N". For example, if somebody /shouts "Hey go to the Fort Ludios if you wanna talk about Thing" and you open the map and see the "Unconfrencing Dungeon" how do you possibly get to Fort Ludios without extensive foreknowledge?

If we just named everything "Kitchen 1" and "Kitchen 2" I could see this working but I'd still much rather have each individual room labelled. That's much close to convention in terms of building maps.

**Comment by MoyTW** [comment]
If we don't end up doing a minimap (I think the minimap will be probably hard to do? unless we literally just draw the map and center+crop it to your location, but the map *must* be properly proportioned) would replacing it with a dynamic sidebar of "Currently Happening Now" to help funnel traffic be a good idea?

```
Like:
Currently Happening:
* Talks! [[theater link]]
* Leif's Thing! [[link to thing]]
```
```
Currently Happneing:
* "Unconference: DCSS is hard" [[room link]]
* "Unconference: Blue is a nice color" [[room link]]
* "Unconference: Example Unconference" [[room link]]
* "Unconference: Something, Something" [[room link]]
* Leif's Thing! [[link to thing]]
```

**Comment by lazerwalker** [comment]
See https://github.com/lazerwalker/azure-mud/pull/286 for new map behavior

**Comment by lazerwalker** [comment]
I think a 'currently happening now' list (presumably above the mini-map) is a great idea!
