### ISSUE TITLE
Space is Closed bug

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#265]
If I'm a mod, and I do the following actions:
* Close the space
* Log out
* Attempt to log back in
I get past the login screen but the server either refuses to send me information or ??? and can't see Rooms, can't progress, etc. I'm not 100% sure it wasn't caused by ban/unban changes I was making, either. I fixed it by just going into Redis and flipping it.

This isn't a huge issue because we have a bunch of mods on prod who can flip it and we can also use Redis if we need to. Just something to be aware of.

**Comment by lazerwalker** [comment]
I'll look into it, but my assumption: `isRegistered` now returns data about whether the logged-in user is a mod. I suspect something, either on the client or on the server, is breaking with that check.

**Comment by lazerwalker** [comment]
I agree we can technically work around this if need be, but I'm taking "avoid manually modifying Redis during the weekend of the event itself" as a minor engineering and process goal :)

**Comment by lazerwalker** [comment]
FWIW, I am unable to reproduce this.

I suspect my fix for #279 will also end up resolving this for you — will nudge you to test when that's merged in.

**Comment by lazerwalker** [comment]
@MoyTW that fix worked for Britta, so it would be cool if you could test this again on the account you experienced this with. You'll want to un-mod and re-mod that account from a different one.

**Comment by MoyTW** [comment]
Seems fixed.
