### ISSUE TITLE
People logging in with Google have a Twitter: field in their profiles with their email addresses

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#270]
![image](https://user-images.githubusercontent.com/62489292/94330163-d3615900-ff8f-11ea-845d-eea7e07428c4.png)

**Comment by lazerwalker** [comment]
This is fixed for new users. Existing Google users will need to manually change it, but the profile edit screen now has a discrete 'twitter' field.
