### ISSUE TITLE
Think about video vs audio chat

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#273]
This is likely low enough priority we won't get to it by the event, but wanted to word-vomit anyway.

Right now, we default to video chat, although you can disable your camera (and theoretically in the future can disable others'). 

Videochat is more communicative but more daunting and emotionally exhausting. Audio has a lower emotional barrier to entry. 

Our current design encourages video over audio-only chat. I'm not sure this is the right choice. Worth thinking about whether we want to nudge people towards videochat, or if we by default put them in audio and then give them ways to opt-in to vide.

When I say I'm not sure our current solution is the right choice, that isn't me saying "we should be more audio-focused". I legitimately don't know the right answer here.

**Comment by dvanduzer** [comment]
It looks like this could be treated on... spectra? This new-ish project is very promising: https://github.com/highfidelity/Spatial-Audio-API-Examples/tree/main/experiments/nodejs/videochat-twilio
