### ISSUE TITLE
Building unconferencing rooms

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#274]
As discussed in the 09/27 meeting:

Fixed set of “Unconference” rooms (~4 rooms?)
Put a Note Wall in each Unconference Room
Disable our native Video chat
Each room has its own Zoom link
Generated ahead of time is ideal

I'm willing to take on the first design pass but how to include them in the map will have to be handled by someone else (@lazerwalker ?) That's especially important if we want to drop the left sidebar room list (#263 )!

Relatedly, and also worth asking - do we want people to be able to wander into and out of those rooms at other times, explicitly or implictly? I could see having the ASCII map have two 'sections' that imply the "Unconferencing Dungeons" are disconnected from the "main" event space, even if you *can* click to enter them at any time, perhaps?

**Comment by MoyTW** [comment]
Yeah maybe have a gate in front of them?

The other question is where we're putting this note wall. Maybe we could have a Unconfrencing Gate or something that has the note wall...?

**Comment by lazerwalker** [comment]
I think all subareas like unconferencing will likely have some sort of entry/lobby room (see #263), which could be themed as a gate. You choose to go to the "Unconferencing Gate" or "Unconferencing Dungeon" or whatever, and from there you have the ability to move to the various unconference rooms.

My instinct is that it's fine if the unconferencing rooms are always available -- my default position is to avoid needing to actively add the ability to contextually lock/unlock certain rooms without a server deploy unless there's a good reason to keep them closed.

@kawa-kitsuragi if you're interested in learning how to add new rooms yourself, check out https://github.com/lazerwalker/azure-mud/blob/main/server/src/room.ts. Manually re-drawing the map needs to happen separately, but adding a new entry to this object with the appropriate data will cause a new room to exist.

**Comment by apepers** [comment]
I've created a lobby sort of room, and 6 Nethack themed unconferencing rooms based on Kawa's suggestions. Haven't put up the pull request yet since I would to make sure links between rooms are working and at least add the lobby to the map, but if you want to take a peek it's in the unconferencing-rooms branch.
