### ISSUE TITLE
Hosting costs?

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#275]
@lazerwalker do we have concerns with hosting costs? We're tossing up screenshots in the Showcase and the Peglin dev asked if we can include a video. The video works out fine with regards to layout, but it's 2.4 MB and I just wondered if I should be checking on the image sizes, so we don't get hit with a surprise bill.

**Comment by lazerwalker** [comment]
Not an issue at all. We're hosting the frontend on GitHub Pages, which is 100% free, and we're nowhere near their gigantic invisible limits for what 'unlimited' means.
