### ISSUE TITLE
Cap video chat size at 8

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#284]
Okay, so, we expected video chat to be a thing for small groups, not like 40 people, and we're aware that it'll sort of explode if 40 people try to video chat at once. Simultaneously we want to encourage small-group communication. Capping video chat at 8, then replacing the "Join Video Chat" with "Video Chat Is Full" and just having a reasonable room/person ratio seems like it solves most of that, right?

There's #215 which would conflict with this but we already have rooms that Not Chat and it'd be essentially identical.

**Comment by lazerwalker** [comment]
I think this is a great idea!

If #215 gets implemented, I suspect it's totally fine if we also just silently let already-video-on people join "full" videochats. Like, at this point I suspect whichever behavior ends up being less work to code.

**Comment by MoyTW** [comment]
#296
