### ISSUE TITLE
Minimap fixes & bounding boxes

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#290]
Issues with minimap:
* Games Showcase West/East are reversed
* A bunch of the bounding boxes are overlapping/off, making it really confusing to navigate

We should *really* get this fixed before conference start, it's making navigating super annoying. Also if possible it might be helpful to have the bounding boxes shaded differently so the clickable area is obvious and you don't have to watch your cursor.

**Comment by MoyTW** [comment]
Issue is unrelated to the refresh issue - did you mean #291 ?

**Comment by lazerwalker** [comment]
D'oh, sorry, yep, saw "minimap fixes" and "high priority" and jumped to conclusions 😂

**Comment by MoyTW** [comment]
Ok, we've investigated and figure the bounding boxes are browser compatibility issues. The solution to that is to just make it bring up the full map when you click the minimap.
