### ISSUE TITLE
"Happening Now" in sidebar

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#293]
It'd need to have:
1. Clickable links that bring you to the content
2. Dynamic content so the admins can update it
3. Somebody who's responsible for updating it

...hmm. #3 might be iffy.

I wonder if we could tie it into the schedule...?

**Comment by lazerwalker** [comment]
as long as we're okay forgoing being able to dynamically pick up on player-driven spontaneous events, this is something that could theoretically (dev time permitting, etc) be scripted ahead of time instead of needing live updates.

**Comment by MoyTW** [comment]
Adding this + everything else already on the sidebar makes it implausibly long, to the point where it starts stretching the page. Hmm.

**Comment by MoyTW** [comment]
I'm gonna shelve this for a bit, but if I do come back to it I'm leaning towards making it a modal on the same conceptual level as the map and putting up a button right above the "Map" button.

**Comment by lazerwalker** [comment]
If you do come back to it, and if it's all pre-scripted, could also be good to tie it into the schedule so that if there's a talk going on that specific talk also shows up
