### ISSUE TITLE
Add unconference rooms to map

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#304]
See title.

**Comment by apepers** [comment]
Will we add just the unconferencing lobby to the map and let people get to the sub-rooms with just the hyperlinks? I remember that being a plan at one point but now our map does seem able to handle more rooms.

**Comment by lazerwalker** [comment]
My plan is to add proper rooms on the map in, I think that'll be more obvious. Current plan is to put everything to the right of the theater.
