### ISSUE TITLE
Persistence counts are not working correct on the map

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#311]
I believe most/all of the "people" are ones who actually shouldn't be in the space (since we're closed and they should have been kicked out)

I suspect this points to a logic bug in what it means for someone to "disconnect" and not wiping out data in all places we should.

![Screen Shot 2020-10-02 at 2 17 42 PM](https://user-images.githubusercontent.com/821238/94956369-0e94e800-04ba-11eb-81e5-78cedd827635.png)
![Screen Shot 2020-10-02 at 2 17 15 PM](https://user-images.githubusercontent.com/821238/94956370-0e94e800-04ba-11eb-8285-4b49412ae80c.png)

**Comment by MoyTW** [comment]
ayuuuup there's some issues here.

![Screenshot from 2020-10-02 13-24-42](https://user-images.githubusercontent.com/1434086/94966787-b3132c00-04b2-11eb-9d2a-cac69273b700.png)

**Comment by MoyTW** [comment]
Heartbeat works off of `getActiveUsers`, checking key `activeUsersList`, which is also what the whisper code checks. So, if somehow katherine is not in `getActiveUsers` but *is* in the roomData, then that would cause this, I think.

**Comment by MoyTW** [comment]
Yeeeep. That's what's happening. She is considered inactive, but never got removed from the room.

![Screenshot from 2020-10-02 13-35-38](https://user-images.githubusercontent.com/1434086/94967695-6c263600-04b4-11eb-8669-edea90445f29.png)

**Comment by lazerwalker** [comment]
Fixed the map issue. Let's migrate heartbeat presence discussion to #221
