### ISSUE TITLE
Can't scroll down on map modal

### ISSUE THREAD

**Issue by brittag** [lazerwalker/azure-mud#322]
When I'm in the map modal (this view):

![Screen Shot 2020-10-02 at 6 00 05 PM](https://user-images.githubusercontent.com/391313/94979698-1adc6d80-04d9-11eb-90cb-8485f69281f5.png)

I can scroll side-to-side, but I can't scroll down to see the rest of the map. It looks like when I try to scroll up and down, the info _behind_ the map scrolls up and down instead of the map.

I'm using a scrolling gesture on a Mac laptop trackpad, using Chrome, browser window at about 1340x690.

It's not a blocker or anything since we also have the list.

**Comment by MoyTW** [comment]
Oh, wow! Can confirm - I suspect something's changed because it used to let you scroll when your window was smaller than the map.

**Comment by MoyTW** [comment]
(Chromium, Firefox on Ubuntu)
