### ISSUE TITLE
Minimap misaligned

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#333]
Still works as a button, though. Chrome, Windows 10

First noticed with the foyer/study, there was no map
![There's no minimap on the left at the foyer - probably scrolling past the bottom](https://user-images.githubusercontent.com/62489292/94994966-02b42f00-0569-11eb-913a-4f73060f0ef7.png)

![Same at the study](https://user-images.githubusercontent.com/62489292/94994995-2ecfb000-0569-11eb-8568-fa54c51b7d13.png)

In the kitchen it's off but technically okay
![image](https://user-images.githubusercontent.com/62489292/94995019-59216d80-0569-11eb-9635-04a956543d13.png)

It's perfect in the lounge. An alignment issue?
![image](https://user-images.githubusercontent.com/62489292/94995032-7b1af000-0569-11eb-9b4a-1241abe478c5.png)

**Comment by lazerwalker** [comment]
Hah, I fixed this before I even saw this 😂

Probably better to bring up issues directly in Discord today rather than on here.
