### ISSUE TITLE
Migrate video chat over to Azure Communication Service

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#363]
Secondary considerations other than just implementing chat:
* Confirm/investigate whether they support transcription, translation, and text-to-speech
* Showing which people are in videochat

**Comment by bengreenier** [comment]
Came here to ask about exactly this! 😄 

Looks like [the public featureset](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features) doesn't currently include transcription/translation/text-to-speech (I can share some more info internally, if that would be helpful) but does include rosters (showing who is in the "call"). 

As I understand it, ACS behaves most similar to Teams today which means there's some scale limits (which I can't find documented) - They should tolerate a higher number of folks than a mesh call of webrtc <-> webrtc clients, though.

**Comment by lazerwalker** [comment]
Ah, interesting @bengreenier! Feel free to ping me on Teams if you think there's internal info that you think is relevant. Otherwise: do you know if it's possible to connect to an AV stream from a server instead of a web browser or mobile app? I'm curious if I could spin up a service that does nothing but generate transcription/translation data from the audio feed via Azure Cognitive Services and pipe that along to clients.

FWIW, I'm not concerned about scale. I think broadcasted talks would still go through Twitch/YouTube, and the intended use case for this should fit well within what Teams can handle (probably max ~10 people for small in-room videochats, closer to ~30 max for unconferencing)

**Comment by bengreenier** [comment]
>  Feel free to ping me on Teams if you think there's internal info that you think is relevant.

I'll reach out!

> do you know if it's possible to connect to an AV stream from a server instead of a web browser or mobile app? I'm curious if I could spin up a service that does nothing but generate transcription/translation data from the audio feed via Azure Cognitive Services and pipe that along to clients.

All I can say here is that scenario seems very compelling 😸 

> FWIW, I'm not concerned about scale. I think broadcasted talks would still go through Twitch/YouTube, and the intended use case for this should fit well within what Teams can handle (probably max ~10 people for small in-room videochats, closer to ~30 max for unconferencing).

Oh gotcha - That makes sense, sounds like a good fit then.

**Comment by lazerwalker** [comment]
For various reasons, the current public preview of ACS is not suitable for our purposes.  Once the `twilio` branch gets merged into main, we will be providing this same functionality with Twilio Programmable Video instead, but there is still a drop-in ACS implementation included in the repo.

My intent is to eventually try to switch back to ACS at some point in the future, but no idea when that will be.

**Comment by patricksevat** [comment]
Hi @lazerwalker could you elaborate on the reasons why ACS is not suitable?

**Comment by lazerwalker** [comment]
The biggest dealbreaker is that joining a new room as a participant can take upwards of 10-15 seconds, which is a dealbreaker for letting people fluidly move between rooms and quickly join/leave videochat. ACS is still in public preview, which means this very well may change sooner rather than later, but for now using ACS for many-to-many chat really isn't a great fit for this specific use case.
