### ISSUE TITLE
Twitter auth failing on missing auth path

### ISSUE THREAD

**Issue by scottcain** [lazerwalker/azure-mud#378]
I imagine this is a configuration issue on my end, since I'm still a fumbling around newbie with several of the technologies involved.  I feel like I have everything setup correctly in Azure and Twitter apps, and I have an nginx server running at http://gmod-mud.scottcain.net/.  While it displays the initial, unaltered "Roguelike Celebration" page, clicking on the Twitter login makes a request for 

http://gmod-mud.scottcain.net//.auth/login/twitter?post_login_redirect_url=http%3A%2F%2Fgmod-mud.scottcain.net%2F

But this returns a 404 because there is not .auth path in the dist directory.  Is this perhaps something that I need to create, something that should be generated by npm, or something that needs to be added to the repo?

**Comment by lazerwalker** [comment]
I assume your SERVER_HOSTNAME variable in the src/config.ts file is pointed towards http://gmod-mod.scottcain.net, when it should be pointed towards the hostname of your Azure Functions backend. If you've configured Azure Functions auth correctly, the .auth path should exist on there.

**Comment by scottcain** [comment]
Ah, I figured it was a simple configuration issue, thanks.

Now I've gone from a 404 to a 500, which suggests that I also have something misconfigured at Azure or Twitter.  Since the message isn't particularly verbose, I can't really tell which.  Any suggestions on where to look next?

Also, I don't know how you like to track issues/user support stuff; I can create a separate issue if you like.

Thanks,
Scott

**Comment by lazerwalker** [comment]
Hmm. What's the endpoint that's 500-ing? Normally I'd point you to the Azure Functions live log stream (you can access it either from the Azure Portal when looking at your Function App or using the VS Code extension), but assuming it's an Azure Functions login URL I'm not sure that will show errors, since that isn't code you've written/deployed yourself. But worth trying?

For now, keeping stuff in this thread is fine! Thanks for asking.

**Comment by scottcain** [comment]
Found it.  Twitter was misconfigured.  In the readme, it says to use`https://your-function-app.azurewebsites.net/.auth/login/twitter/callback` but rather than using my function app name I used the resource group name (they are similar but not the same).  I'll close this issue (but presumably be back with more :-) 

Thanks for your help!
