### ISSUE TITLE
link on page after login is incorrect

### ISSUE THREAD

**Issue by scottcain** [lazerwalker/azure-mud#384]
When a user logs in via Twitter, he gets first the Twitter page that informs the user the Twitter is supplying (whatever--identity or some such), and then redirects to a page that looks like this:
<img width="407" alt="Screen Shot 2020-11-04 at 3 49 47 PM" src="https://user-images.githubusercontent.com/274751/98181072-4f1bc300-1eb7-11eb-8fb3-894d8797eeb7.png">
The problem is that the link is to the function app page on Azure, not the web client.  I don't see a configuration parameter for this, and I'm guessing it needs to be fixed either at Twitter or on Azure.

**Comment by lazerwalker** [comment]
I believe that's an option on the Twitter side — it tries to redirect you to wherever you came from, but that site needs to be on a list of allowed domains you give Twitter.
