### ISSUE TITLE
Can type /help to see a cheatsheet of commands

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#39]
I think this is just a hand-written description of common actions, with plain English text describing how to move around in the MUD. I think the focus here is specifically on text commands, since hopefully mouse-driven interactions should be obvious to people who don't want to type MUD-y commands.

Bad ideas:
* Programmatically generate this from some single source of truth about which `/commands` exist (we want friendly English text!)
* Try to show everything that's possible. This is going to get real weird once we add in an object model and interactable items. That also destroys some of the magic of discovery!

**Comment by kawa-kitsuragi** [comment]
(I'd like to assign this to myself, but I don't seem to be able to.) 

Here's a first draft of that that /help text would be. 

> Welcome to the event! Here's some commands you can use. There may be others - try things out!
> 
> /help - Display this message.
> /move \<room\> - Moves you to another room. 
> /me \<Message\> - Outputs your message to make it look like you're doing an action. For example, /me waves will look like "<em>[Username] waves</em>"
> /mod \<Message\> - Send a private message to event moderators.
> /whisper \<User\> \<Message\> - Send a private message to a specific person. 

Next steps:
- [ ] Should any of these descriptions be revised?
- [ ] Are there other commands we want to include? 
- [ ] How do we format it so that the [Username] displays the user, and the whole /me example indeed looks like it 'should'?
- [ ] I'll need some help actually integrating this into a command.

**Comment by lazerwalker** [comment]
A few things!

- I've added you as a collaborator, which should allow you to assign issues to yourself. The way GitHub works, you'll need to accept the email invite before you have access.
- I've added a separate issue to track adding support for a `me` command: #68
- Thinking about this, the way I'd actually want to implement this is relatively complicated and dynamic (e.g. wanting to contextually surface commands that might only be available in certain rooms) -- "good first issue" was a mislabel here :joy:. I think the text you've added is a great start I'll build on, but I think I'm gonna take this on myself, or at least until I can chunk it out into more manageable things.

**Comment by lazerwalker** [comment]
Sigh, giving up on my dynamic help for the purposes of the meetup 🤣

This should also have 2-3 sentences explaining at a high level what the space is, should be linked in the name dropdown, and should maaaaybe also describe how to do things with the mouse in addition to /commands

**Comment by MoyTW** [comment]
I was thinking of making it a button and not hidden behind the name dropdown. Hiding it behind the name dropdown is much less accessible, I think, but I'm not a UI person. I played around with where to put the button and couldn't really find a great place, though - see 

![Screenshot from 2020-08-28 15-52-04](https://user-images.githubusercontent.com/1434086/91621218-33d88880-e947-11ea-9997-189816338923.png)

is kind of janky. Will it in the menu if there's strong feelings on it.

**Comment by lazerwalker** [comment]
@MoyTW Some code I just merged to main adds a handful of other sidebar menu items that open modals, this would go perfectly there.
