### ISSUE TITLE
Highlight active speakers

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#446]
If somebody is speaking, add a border around their videochat profile (meaning, their video + name if they're sending video, or their name + black square if just audio).

There's some old code (probably in webrtc.ts) to analyze audio feeds, but I'm 99% sure Twilio exposes an "active speaker" property that will tell us who the active speaker is.

Our old code conceptually says "if somebody is talking, highlight them", whereas Twilio specifically figures out "this is the one most prominent speaker". I don't have strong thoughts on which model is better; I think our primary concern is speed of implementation.

**Comment by MoyTW** [comment]
This is kind of done - it highlights the 'loudest' track, which is not *necessarily* the active speaker (could be environmental noise)

it also doesn't highlight *you* if you're loudest
