### ISSUE TITLE
"Leave Chat" button leaves the chat completely

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#457]
Related to #456

**Comment by lazerwalker** [comment]
I'm 90% sure this works as intended, both from looking at the code paths (`twilioChatContext#leaveCall` is never actually called by anything!) and from testing with 2 browsers on a computer. However, that computer had only one video input, which made testing a bit janky. 

Will run a test from two computers before closing this.

**Comment by lazerwalker** [comment]
Confirmed working as expected. If people are broadcasting video, then you broadcast video, then you click "leave chat", you can still see/hear folks.

I'm renaming that button to (contextually) "Turn off Camera", "Turn off Camera and Mic", or "Turn off Mic"
