### ISSUE TITLE
Should we require real names?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#49]
In favor of real names: 
* Helps tie things back to being a real conference with real people
* Makes it easier for us to tie CoC violations back to real people
* Feels more "grown-up" than just handles/usernames

Against real names:
* Some people, who are not trolls, might prefer to be pseudonymous, and that's totally valid.
* Needs to be worded correctly to make it clear we're not asking for a legal name.
* Yet another thing to ask people. Less info is better!
* UI/design complications we want to let people say "show me names instead of usernames"

I'm currently mildly against.

**Comment by kawa-kitsuragi** [comment]
I am also mildly against, particularly since I don't use my wallet name in this community. 

To 'tie CoC violations back to real people', perhaps we can encourage/require an email field that matches the email of the Eventbrite ticket - or even a field where you have to enter your eTicket confirmation number?

**Comment by lazerwalker** [comment]
Just for the sake of argument, I want to emphasize that "real name" != wallet/legal name.

The assumption would be the same as Slack: e.g. in my case, my username would be "lazerwalker" but my "real name" would be "Em Lazer-Walker" despite that not being my legal name.

**Comment by annie** [comment]
maybe we can copy Slack here and call it "Display Name". in the chat, if a user has a display name, we render that instead of the username. i also think "Display Name" makes it more obvious that this doesn't have to be your legal name.

**Comment by lazerwalker** [comment]
Yeah, the overwhelming feedback I got on Twitter is "Real Name" is definitely not correct 😂

I think I've also realized that "get your full name for CoC violations" is the wrong approach — the main benefit of this is to be able to help humanize people and make them seem less like just chat handles.

I want to play around with having part of the profile edit screen be literally making a "Hello My Name Is"-style name badge, and using that metaphor to help make it clear what should go in 'name'.

**Comment by lazerwalker** [comment]
I think our current solution is fine!
