### ISSUE TITLE
A room with a post-it note wall

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#5]
A concrete usecase is unconferencing, but this will have a whole bunch of other useful purposes in the world (both logistical things like posting feedback about the conference/space, and social/playful in letting people express themselves in the world)

Some questions:
* Are all post-its always visible? Is there a "most x recent ones visible" type thing?
* For a given post-it wall, can a single user post more than one message, or does a new message override the previous one?
* What is the UI? Do we show all messages in the description, or is there a clickable link to print them out?
* Can you delete your own messages?

I assume post-it notes are tied to a given 'note wall', and cannot be moved freely from room to room.

**Comment by dvanduzer** [comment]
i've been experimenting with https://github.com/automerge/pushpin recently, for its multi-user data replication properties. it is explicitly impossible to delete history (although it is possible to edit content out of the "canonical version" of a document)

**Comment by lazerwalker** [comment]
That looks really cool!

To clarify, though, this issue is about adding some sort of simple 'post-it wall' feature into our own infrastructure. Specifically, I think this means:

- If a room has post-it notes enabled, it has metadata about what post-it notes are available (sent to the client when you move to the room, and real-time updates are also sent). When rendering a room, render the post-it notes somehow (with design challenges around how to manage large numbers of post-it notes)
- Players can create new post-it notes in enabled rooms (presumably both as a /command and via a UI), specifically for that room
- Players can +1 existing notes, and the number of +1s / who +1ed a note is visible on that note
- Players can delete their own notes (and mods can delete any notes)

The primary use case at first is for letting attendees plan unconferencing, as well as a "feedback" wall. Once this exists, I could see it being repurposed for other purposes.

**Comment by lazerwalker** [comment]
Checklist for my own use:

- [ ] Can add notes via UI
- [ ] Can add notes via CLI
- [ ] Can remove notes that you've posted, or if you're a mod
- [ ] Can like a note
- [ ] Can unlike a note
- [ ] Styling (is this modal or not?)
- [ ] Make usernames a <NameView>

**Comment by lazerwalker** [comment]
For context: 

![Screen Shot 2020-08-16 at 10 56 01 PM](https://user-images.githubusercontent.com/821238/90353558-87c4a280-e014-11ea-9f78-c7a30a746678.png)
