### ISSUE TITLE
Public /go messages "spoil" hidden rooms

### ISSUE THREAD

**Issue by kawa-kitsuragi** [lazerwalker/azure-mud#531]
The current behavior is that everyone can see when a user leaves a room, and where they're going; you can also see where a user came in from.

This is great and maybe even ideal in public spaces, but does spoil the riddle puzzles, if you're standing in front of a riddle and see someone /go [solution]! 

Solution is to give an alternate message if someone `/go`-es to/from a room where `hidden = true`. 

![image](https://user-images.githubusercontent.com/62489292/137410187-4a4a4177-7df2-42cf-8324-dc6ee3a402f5.png)

**Comment by apepers** [comment]
Closed with merged in change
