### ISSUE TITLE
Moderators should have the ability to delete messages

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#79]
So, this is a bit wonky. Because chat is ephemeral, "deleting" a message doesn't mean deleting it from a centralized source of truth. It means sending out a "recant" message that instructs clients to remove that message from their internal list of messages.

This is weird for two reasons:
1. Messages don't have unique IDs. So we presumably need to send the entire message body for us to pattern-match on
2. We don't know exactly who received a message — "which users were part of a SignalR group at an arbitrary point in the past" is not data we store. So we probably need to send this out to all users.

Combining those together, this means that offensive content is being sent in plaintext to all connected clients, even if that data is not being presented to users. This feels... weird?

To think about.

**Comment by lazerwalker** [comment]
[For now, I'm okay saying "let's just send the plaintext of the message to all connected clients".

This feels like a manageable chunk of work for someone who's excited to get started on the server. Things this needs:

1. On the client, if you are an admin, we will need a right-click menu on every public message type (ChatMessage, EmoteMessage, ShoutMessage) that has an option to "Remove" or "Delete" (see NameView.tsx for a good example of these menus). Presumably it should confirm via browser prompt before sending a message to an endpoint containing the message info.

2. A new HTTP endpoint needs to exist to receive that. It needs to check the user is a mod, and then if so, send out a "you should delete this" message to all users with the contents of the message

3. When that delete message is received, all clients should go and remove messages from their local message store that have the same sender and text content.

**Comment by MoyTW** [comment]
`Messages don't have unique IDs. So we presumably need to send the entire message body for us to pattern-match on`

Is there something fundamentally incompatible with having the client generate a UUID and sticking it into the message object, and our current design? I don't think so, but did I miss something?

**Comment by lazerwalker** [comment]
That's totally reasonable! I was mildly against the idea of cluttering up every chat message and our client data with a few more bytes for a UUID we only use for moderation, but I strongly suspect after I've slept on it I'll conclude that's irrational and silly 😆

**Comment by MoyTW** [comment]
Current message types:

```
export enum MessageType {
  Connected = 'CONNECTED',
  Disconnected = 'DISCONNECTED',
  Entered = 'ENTERED',
  Left = 'LEFT',
  MovedRoom = 'MOVED',
  Chat = 'CHAT',
  Whisper = 'WHISPER',
  Shout = 'SHOUT',
  Emote = 'EMOTE',
  Mod = 'MOD',
  Error = 'ERROR',
}
```

Of those, we want to be able to delete the following:

* Chat
* Shout
* Emote
* Mod

I don't think mods should be able to delete whispers, but we should let users block other users (that'd be a different issue).

**Comment by lazerwalker** [comment]
This all makes sense to me! (a few days later, I'm also expectedly okay with adding a message UUID😂)

Opened https://github.com/lazerwalker/azure-mud/issues/94 and https://github.com/lazerwalker/azure-mud/issues/95
