### ISSUE TITLE
Consider getting rid of the room side list in favor of a "map" screen

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#86]
My concern: always seeing every other room, and being able to move with a single click, encourages FOMO rather than either enjoying your current conversation or encouraging spontaneous exploration.

My proposal:

* The "you can go to [the bar] or [the kitchen]" hypertext prompts show how many people are in each room. e.g. "You can go to the bar (5) or the kitchen (23)". This gets abstracted out into some sort of "RoomNameView" (a la NameView) that renders presence numbers and renders a video icon if there is an active videochat happening.
* The sidebar has no channel names, but a "map" button
* The map button displays a full-screen map of the space, potentially rendered in Rogue-like ASCII. Each room is named and has a user count / video icon if playing video
* Next to the map is the existing list of room names
* Clicking a room (either in the list or the map) moves you to that room and closes the modal.

Pros:
* Encourages people to stay in conversations
* Encourages exploration via the hypertext links, which can lead to more spontaneity
* The "map" emphasizes the spatiality and physicality of the space
* An ASCII map of our space would be cute as hell

Cons:
* Makes the space slightly less understandable to non-"gamers" by losing the Slack/Discord-style UI
* What goes in the left sidebar instead?

I strongly believe this is worth implementing before the meetup so we can test if the con overrules all of the pros.

**Comment by lazerwalker** [comment]
I'm not sure this is the correct choice, but increasingly convinced it's the right thing to have in place for the meetup. Seeing how users respond to not having a left channel sidebar will be more instructive than the alternative.

**Comment by MoyTW** [comment]
Threw together a prototype for discussion here: https://github.com/lazerwalker/azure-mud/compare/minimap-playground - branch supports clicking. The YOU ARE HERE is always the center tile, like a game minimap. If we add in like...another five rooms (which we might want to do) that's when it'll be important to move with the user.

![minimap-you-are-here](https://user-images.githubusercontent.com/1434086/90221887-db8a7e00-ddbf-11ea-87c3-9fec2907346d.png)

![minimap-you-are-here2](https://user-images.githubusercontent.com/1434086/90221945-f3fa9880-ddbf-11ea-9bb6-3299ba79f05f.png)

**Comment by lazerwalker** [comment]
This looks awesome! I'd been imagining it would purely be a modal view you had to click through to, but I think this works awesome as a sort of 'mini-map'. Would still probably be good to have a larger full map view we can toggle.

I'd really like to make it into a Rogue-looking ASCII map instead of boxes -- I may take a stab at adding a few more rooms to the space and then hand-drawing an ASCII layout.

**Comment by lazerwalker** [comment]
I have a hand-drawn ASCII map. On my plate is figuring out how to squish that into the existing sidebar branch code, and also building a modal with a larger view.

**Comment by lazerwalker** [comment]
This is janky and still needs a bit more work, but I'm super happy with how this is looking

![Screen Shot 2020-08-28 at 1 02 11 PM](https://user-images.githubusercontent.com/821238/91593792-c882bc80-e92e-11ea-861b-1a77dd746d22.png)

**Comment by lazerwalker** [comment]
Couldn't figure out how to make this map style look good in the sidebar. Current compromise is having a list in the sidebar, with a link to open a modal.

![Screen Shot 2020-08-28 at 7 30 16 PM](https://user-images.githubusercontent.com/821238/91622384-e8cd6e00-e964-11ea-8707-e8fd2ef879cd.png)

![Screen Shot 2020-08-28 at 7 29 21 PM](https://user-images.githubusercontent.com/821238/91622375-dce1ac00-e964-11ea-98c8-cfaa24ae0c2c.png)

**Comment by lazerwalker** [comment]
Could definitely use improvements (e.g. colors, bold text for the room name, a video stream indicator), but I think this is a solid start for the meetup.
