### ISSUE TITLE
Connected/Disconnected/Moved Spam

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#93]
I'm concerned about the quantity of messages drowning out conversation. This varies a lot by volume - for example, if there are 3 people chatting, and then another person joins, it makes sense to display that. But in, say, the theater room, it'd just make things unreadable.

Possible ideas:
* Just don't display those messages
* Only display them when the number of people is under an arbitrary limit
* Display them, but in a sidebar/different UI element than the words element

**Comment by lazerwalker** [comment]
This is a good point!

I'd be inclined to view the meetup as a practical test of what's actually a problem. I think I'd be okay trying to not display them over an arbitrary room count, but I'd want to hold off on either not displaying connect/disconnect/move messages or displaying them somewhere else until we see how they interact with actual player use patterns. I think seeing how the current solution (or the current solution + an arbitrary limit) falls over during the meetup will be a more useful and productive test than trying to design an ideal solution now?

(re: displaying them somewhere else, it's worth thinking about whether there would be other uses for 'toaster' notifications – an ephemeral pop-up seems like it might feel more natural than finding a different persistent UI to shove that data into?)

**Comment by lazerwalker** [comment]
Definitely needs fixing :)

The design fixes I'm musing over:

- Show them in lighter text (I don't think this is enough)
- Show a dedicated join/leave feed in the left sidebar (this feels like something people will ignore)
- Only display them when number of users in a room is under a certain number
- Have some sort of ephemeral way to display them 

The fourth one is the only new idea.

My current gut instincts:
- Only showing them in rooms under, say, 10 people still feels like a reasonable idea to test. If only 4 of you are talking, somebody leaving/entering is valuable information.
- I'm skeptical of showing them in a dedicated sidebar, but this is easy to prototype
- I think an ephemeral pop-up is theoretically the best solution, but don't know what it should actually look like

**Comment by MoyTW** [comment]
One thing to note is that it did at least make things feel more active. Without those it'd definitely have felt more dead.

Other possible ideas:
* Batch all user entries/exits, so that the most you get is every other line. This admittedly converges to "50% of all chat is user connect/disconnect/enters/exits" in high-traffic areas, which still isn't great, but at least it's better than a solid wall. Combined with differentiated text this seems...okay?
* Make the user list a first-class citizen and maybe, like...animate people going in and out? Like uuuuh...make it look like a non-ASCII this:

```
            ARCADE
    +---------------------+
    |  Bob                |
    /       Alice         / Eve
    |                     |
    +---------------------+
```
and then, like, Eve slides in from the left door and goes to a random position in the room to indicate Eve is present. Actually, I kind of like this, because it gives a feeling of emptiness/crowdedness.

**Comment by MoyTW** [comment]
MVP fix plan:
* Create a setting for "Display move actions under X people"
  * If the room has X or less than X people, it shows any further move actions
  * If the room has more than X people, hides all move actions
  * Setting defaults to 6
* Condense multiple move actions onto one line
